/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.scoring.GUI.panels;

import com.scoring.globalvariables.GlobalVariables;
import com.scoring.globalvariables.TeamMatchVariables;
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author AuroLed
 */
public class TossConfirmPanel extends javax.swing.JPanel {

    /**
     * Creates new form TossConfirmPanel
     */
    private String tossOwnTeam = null;
    private String tossOwnTeamDecision = null;
    public static String tossResultText = "Won The Toss And Choose To";

    public TossConfirmPanel() {
        
        initComponents();
        this.setVisible(true);
        this.setBackground(new Color(66, 125, 102));
        this.setBounds(50, 50, 1200, 620);

        toss_decision_panel.setVisible(false);
        toss_result_field.setVisible(false);

        loadTeamsForToss();

    }

    private void loadTeamsForToss() {

        DefaultListModel<String> defaultListModel = new DefaultListModel<>();

        defaultListModel.addElement(TeamMatchVariables.homeTeam);
        defaultListModel.addElement(TeamMatchVariables.awayTeam);

        toss_selection_list.setModel(defaultListModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        toss_field_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        toss_selection_list = new javax.swing.JList<>();
        toss_decision_panel = new javax.swing.JPanel();
        chooseOption_header = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        toss_team_decision_list = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        toss_result_field = new javax.swing.JTextArea();
        toss_confirm_btn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Match Toss");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 60, -1));

        toss_field_panel.setBackground(new java.awt.Color(255, 204, 204));
        toss_field_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Select The Toss Winning Team");
        toss_field_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 170, 20));

        toss_selection_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        toss_selection_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        toss_selection_list.setAlignmentX(1.0F);
        toss_selection_list.setAlignmentY(1.0F);
        toss_selection_list.setFixedCellHeight(22);
        toss_selection_list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                toss_selection_listValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(toss_selection_list);

        toss_field_panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 300, 50));

        add(toss_field_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 330, 150));

        toss_decision_panel.setBackground(new java.awt.Color(255, 204, 204));
        toss_decision_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chooseOption_header.setText("won the toss and choose to");
        toss_decision_panel.add(chooseOption_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 225, 26));

        toss_team_decision_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Bat", "Bowl" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        toss_team_decision_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        toss_team_decision_list.setAlignmentX(1.0F);
        toss_team_decision_list.setAlignmentY(1.0F);
        toss_team_decision_list.setFixedCellHeight(22);
        toss_team_decision_list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                toss_team_decision_listValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(toss_team_decision_list);

        toss_decision_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 300, 50));

        add(toss_decision_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 330, 150));

        toss_result_field.setEditable(false);
        toss_result_field.setBackground(new java.awt.Color(153, 102, 0));
        toss_result_field.setColumns(2);
        toss_result_field.setForeground(new java.awt.Color(255, 255, 255));
        toss_result_field.setLineWrap(true);
        toss_result_field.setRows(2);
        toss_result_field.setText("sdffffffffffffffffffffffffffffffff ");
        toss_result_field.setToolTipText("");
        toss_result_field.setWrapStyleWord(true);
        toss_result_field.setMaximumSize(new java.awt.Dimension(100, 25));
        toss_result_field.setMinimumSize(new java.awt.Dimension(50, 22));
        toss_result_field.setPreferredSize(new java.awt.Dimension(80, 40));
        jScrollPane3.setViewportView(toss_result_field);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 330, 60));

        toss_confirm_btn.setText("CONFIRM");
        toss_confirm_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toss_confirm_btnActionPerformed(evt);
            }
        });
        add(toss_confirm_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 240, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void toss_confirm_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toss_confirm_btnActionPerformed
        // TODO add your handling code here:

        if (tossOwnTeam != null && tossOwnTeamDecision != null) {
            TeamMatchVariables.currentMatchDetails.setToss_win_team(tossOwnTeam);
            TeamMatchVariables.currentMatchDetails.setToss_win_choose_type(tossOwnTeamDecision);
//            JOptionPane.showMessageDialog(this, "", " ", JOptionPane.OK_OPTION);

            GlobalVariables.tossOwnTeam = tossOwnTeam;

            if (tossOwnTeamDecision.equalsIgnoreCase("Bat")) {
                GlobalVariables.firstInningsBattingTeam = tossOwnTeam;
                if (tossOwnTeam.equals(TeamMatchVariables.homeTeam)) {
                    GlobalVariables.firstInningsBowlingTeam = TeamMatchVariables.awayTeam;
                } else {
                    GlobalVariables.firstInningsBowlingTeam = TeamMatchVariables.homeTeam;
                }
            } else {
                GlobalVariables.firstInningsBowlingTeam = tossOwnTeam;
                if (tossOwnTeam.equals(TeamMatchVariables.homeTeam)) {
                    GlobalVariables.firstInningsBattingTeam = TeamMatchVariables.awayTeam;
                } else {
                    GlobalVariables.firstInningsBattingTeam = TeamMatchVariables.homeTeam;
                }
            }

            this.setVisible(false);
            GlobalVariables.mainScoringForm.remove(this);
            GlobalVariables.mainScoringForm.add(new VerifyDetailsPanel());

        } else {
            JOptionPane.showMessageDialog(this, "Please Select The Toss Own Team And What they Decided To Do First", "Please Select The Teams", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_toss_confirm_btnActionPerformed

    private void toss_selection_listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_toss_selection_listValueChanged
        // TODO add your handling code here:

        if (evt.getValueIsAdjusting()) {
            tossOwnTeam = toss_selection_list.getSelectedValue();
            toss_decision_panel.setVisible(true);

            toss_result_field.setText(tossOwnTeam + " " + tossResultText);

            toss_result_field.setVisible(true);
        }

    }//GEN-LAST:event_toss_selection_listValueChanged

    private void toss_team_decision_listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_toss_team_decision_listValueChanged
        // TODO add your handling code here:
        if (evt.getValueIsAdjusting()) {
            tossOwnTeamDecision = toss_team_decision_list.getSelectedValue();
            toss_result_field.setText(tossOwnTeam + " " + tossResultText + " " + tossOwnTeamDecision);
        }
    }//GEN-LAST:event_toss_team_decision_listValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chooseOption_header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton toss_confirm_btn;
    private javax.swing.JPanel toss_decision_panel;
    private javax.swing.JPanel toss_field_panel;
    private javax.swing.JTextArea toss_result_field;
    private javax.swing.JList<String> toss_selection_list;
    private javax.swing.JList<String> toss_team_decision_list;
    // End of variables declaration//GEN-END:variables
}
