/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.scoring.GUI.panels;

import com.scoring.GUI.MainScoringForm;
import com.scoring.beans.CurrentMatchPlayers;
import com.scoring.globalvariables.GlobalVariables;
import com.scoring.globalvariables.TeamMatchVariables;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author AuroLed
 */
public class VerifyDetailsPanel extends javax.swing.JPanel {

    /**
     * Creates new form VerifyDetailsPanel
     */
    public VerifyDetailsPanel() {

        initComponents();

        this.setVisible(true);
        this.setBackground(new Color(66, 125, 102));
        this.setBounds(50, 50, 1200, 620);

        loadTheEntries();

    }

    private void loadTheEntries() {

        home_teamName.setText(TeamMatchVariables.homeTeam);
        away_teamName.setText(TeamMatchVariables.awayTeam);

        String tossWinningTeam = TeamMatchVariables.currentMatchDetails.getToss_win_team();
        String tossWinningDecision = TeamMatchVariables.currentMatchDetails.getToss_win_choose_type();

        toss_result.setText(tossWinningTeam + TossConfirmPanel.tossResultText + tossWinningDecision);

        loadHomeTeamPlayers();
        loadAwayTeamPlayers();

    }

    private void loadHomeTeamPlayers() {
        // for home team players and captain

        DefaultListModel<String> homeTeamPlayersModel = new DefaultListModel<>();

        ArrayList<CurrentMatchPlayers> currentMatchPlayers = TeamMatchVariables.selectedPlayersMap.get(TeamMatchVariables.homeTeam);

//        System.out.println("players size size size size size   :: " + currentMatchPlayers.size());

        for (CurrentMatchPlayers matchPlayers : currentMatchPlayers) {

            if (matchPlayers.getPlayer_full_name().equals(TeamMatchVariables.homeTeamCaptain) && matchPlayers.getPlayer_full_name().equals(TeamMatchVariables.homeTeamWicketKeeper)) {
                homeTeamPlayersModel.addElement(matchPlayers.getPlayer_name() + " (C)" + " (WK)");
            } else if (matchPlayers.getPlayer_full_name().equals(TeamMatchVariables.homeTeamCaptain)) {
                homeTeamPlayersModel.addElement(matchPlayers.getPlayer_name() + " (C)");
            } else if (matchPlayers.getPlayer_full_name().equals(TeamMatchVariables.homeTeamWicketKeeper)) {
                homeTeamPlayersModel.addElement(matchPlayers.getPlayer_name() + " (WK)");
            } else {
                homeTeamPlayersModel.addElement(matchPlayers.getPlayer_name());
            }

            

        }

        home_teamList.setModel(homeTeamPlayersModel);
    }

    private void loadAwayTeamPlayers() {

        DefaultListModel<String> awayTeamPlayersModel = new DefaultListModel<>();

        for (CurrentMatchPlayers matchPlayers : TeamMatchVariables.selectedPlayersMap.get(TeamMatchVariables.awayTeam)) {

            if (matchPlayers.getPlayer_full_name().equals(TeamMatchVariables.awayTeamCaptain) && matchPlayers.getPlayer_full_name().equals(TeamMatchVariables.awayTeamWicketKeeper)) {
                awayTeamPlayersModel.addElement(matchPlayers.getPlayer_name() + " (C)" + " (WK)");
            } else if (matchPlayers.getPlayer_full_name().equals(TeamMatchVariables.awayTeamCaptain)) {
                awayTeamPlayersModel.addElement(matchPlayers.getPlayer_name() + " (C)");
            } else if (matchPlayers.getPlayer_full_name().equals(TeamMatchVariables.awayTeamWicketKeeper)) {
                awayTeamPlayersModel.addElement(matchPlayers.getPlayer_name() + " (WK)");
            } else {
                awayTeamPlayersModel.addElement(matchPlayers.getPlayer_name());
            }
        }

        away_teamList.setModel(awayTeamPlayersModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        away_teamName = new javax.swing.JTextField();
        home_teamName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        away_teamList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        home_teamList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        toss_result = new javax.swing.JTextArea();
        proceedTo_scoreBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please Verify The Details That You Selected");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 240, 30));
        add(away_teamName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 300, 30));

        home_teamName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_teamNameActionPerformed(evt);
            }
        });
        add(home_teamName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 300, 30));

        away_teamList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(away_teamList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 300, 270));

        home_teamList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        home_teamList.setToolTipText("");
        jScrollPane2.setViewportView(home_teamList);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 300, 270));

        toss_result.setColumns(2);
        toss_result.setRows(2);
        toss_result.setWrapStyleWord(true);
        jScrollPane3.setViewportView(toss_result);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 310, 70));

        proceedTo_scoreBtn.setText("PROCEED TO SCORING");
        proceedTo_scoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedTo_scoreBtnActionPerformed(evt);
            }
        });
        add(proceedTo_scoreBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 300, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void home_teamNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_teamNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_home_teamNameActionPerformed

    private void proceedTo_scoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedTo_scoreBtnActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        GlobalVariables.mainScoringForm.remove(this);
        GlobalVariables.mainScoringForm.add(new MainScoringPanel());

    }//GEN-LAST:event_proceedTo_scoreBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> away_teamList;
    private javax.swing.JTextField away_teamName;
    private javax.swing.JList<String> home_teamList;
    private javax.swing.JTextField home_teamName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton proceedTo_scoreBtn;
    private javax.swing.JTextArea toss_result;
    // End of variables declaration//GEN-END:variables
}
