/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.scoring.GUI;

import com.scoring.globalvariables.TeamMatchVariables;
import com.scoring.threadOperations.BeforeMatchThreadOperatins;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author AuroLed
 */
public class MainScoringForm extends javax.swing.JFrame {

    /**
     * Creates new form MainScoringForm
     */
    private BeforeMatchThreadOperatins beforeMatchThreadOperatins;

    public MainScoringForm() {

        initComponents();
        this.getContentPane().setBackground(new Color(29, 99, 97));
        this.setBounds(0, 0, 1300, 720);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        loadOperations();

        beforeMatchThreadOperatins = new BeforeMatchThreadOperatins();
        beforeMatchThreadOperatins.callBeforeMatchThread();
    }

    private void loadOperations() {
        menu_scrollpane.setVisible(false);
        edit_scrollpane.setVisible(false);
        teams_scrollpane.setVisible(false);
        match_scrollpane.setVisible(false);
        settings_scrollpane.setVisible(false);
    }

    private void scrollPaneVisibilityHandler(String menuType) {

        System.out.println("function called called ");

        if (menuType == "menu") {

            edit_scrollpane.setVisible(false);
            teams_scrollpane.setVisible(false);
            match_scrollpane.setVisible(false);
            settings_scrollpane.setVisible(false);

        } else if (menuType == "edit") {

            menu_scrollpane.setVisible(false);
            teams_scrollpane.setVisible(false);
            match_scrollpane.setVisible(false);
            settings_scrollpane.setVisible(false);

        } else if (menuType == "teams") {

            menu_scrollpane.setVisible(false);
            edit_scrollpane.setVisible(false);
            match_scrollpane.setVisible(false);
            settings_scrollpane.setVisible(false);

        } else if (menuType == "match") {

            menu_scrollpane.setVisible(false);
            edit_scrollpane.setVisible(false);
            teams_scrollpane.setVisible(false);
            settings_scrollpane.setVisible(false);

        } else if (menuType == "settings") {

            menu_scrollpane.setVisible(false);
            edit_scrollpane.setVisible(false);
            teams_scrollpane.setVisible(false);
            match_scrollpane.setVisible(false);
//            settings_scrollpane.setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_scrollpane = new javax.swing.JScrollPane();
        menu_list = new javax.swing.JList<>();
        edit_scrollpane = new javax.swing.JScrollPane();
        edit_list = new javax.swing.JList<>();
        teams_scrollpane = new javax.swing.JScrollPane();
        teams_list = new javax.swing.JList<>();
        match_scrollpane = new javax.swing.JScrollPane();
        match_list = new javax.swing.JList<>();
        settings_scrollpane = new javax.swing.JScrollPane();
        settings_list = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_btn = new javax.swing.JMenu();
        edit_menuBtn = new javax.swing.JMenu();
        teams_menuBtn = new javax.swing.JMenu();
        match_menuBtn = new javax.swing.JMenu();
        settings_menuBtn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu_list.setBackground(new java.awt.Color(76, 133, 131));
        menu_list.setForeground(new java.awt.Color(255, 255, 255));
        menu_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        menu_list.setName(""); // NOI18N
        menu_scrollpane.setViewportView(menu_list);

        getContentPane().add(menu_scrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 104, -1));

        edit_list.setBackground(new java.awt.Color(76, 133, 131));
        edit_list.setForeground(new java.awt.Color(255, 255, 255));
        edit_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        edit_scrollpane.setViewportView(edit_list);

        getContentPane().add(edit_scrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 100, -1));

        teams_list.setBackground(new java.awt.Color(76, 133, 131));
        teams_list.setForeground(new java.awt.Color(255, 255, 255));
        teams_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Choose Teams", "Add Players", "Select Captain" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        teams_list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                teams_listValueChanged(evt);
            }
        });
        teams_scrollpane.setViewportView(teams_list);

        getContentPane().add(teams_scrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 0, 107, -1));

        match_list.setBackground(new java.awt.Color(76, 133, 131));
        match_list.setForeground(new java.awt.Color(255, 255, 255));
        match_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Start Match", "Load Previus Match" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        match_scrollpane.setViewportView(match_list);

        getContentPane().add(match_scrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 0, -1, -1));

        settings_list.setBackground(new java.awt.Color(76, 133, 131));
        settings_list.setForeground(new java.awt.Color(255, 255, 255));
        settings_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        settings_scrollpane.setViewportView(settings_list);

        getContentPane().add(settings_scrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 0, 100, -1));

        jMenuBar1.setBackground(new java.awt.Color(106, 130, 138));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setAlignmentX(1.0F);
        jMenuBar1.setAlignmentY(1.0F);
        jMenuBar1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(1, 2, 2, 2));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(120, 25));

        menu_btn.setText("Menu           ");
        menu_btn.setMaximumSize(new java.awt.Dimension(110, 32767));
        menu_btn.setPreferredSize(new java.awt.Dimension(100, 19));
        menu_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_btnMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_btn);

        edit_menuBtn.setText("Edit            ");
        edit_menuBtn.setMaximumSize(new java.awt.Dimension(110, 32767));
        edit_menuBtn.setPreferredSize(new java.awt.Dimension(100, 19));
        edit_menuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_menuBtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(edit_menuBtn);

        teams_menuBtn.setText("Teams");
        teams_menuBtn.setMaximumSize(new java.awt.Dimension(110, 32767));
        teams_menuBtn.setPreferredSize(new java.awt.Dimension(100, 19));
        teams_menuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teams_menuBtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(teams_menuBtn);

        match_menuBtn.setText("Match");
        match_menuBtn.setMaximumSize(new java.awt.Dimension(120, 32767));
        match_menuBtn.setPreferredSize(new java.awt.Dimension(110, 19));
        match_menuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                match_menuBtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(match_menuBtn);

        settings_menuBtn.setText("Settings                   ");
        settings_menuBtn.setMaximumSize(new java.awt.Dimension(120, 32767));
        settings_menuBtn.setPreferredSize(new java.awt.Dimension(110, 19));
        settings_menuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settings_menuBtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(settings_menuBtn);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_btnMouseClicked
        // TODO add your handling code here:

        if (menu_scrollpane.isVisible()) {
            menu_scrollpane.setVisible(false);
        } else {
            menu_scrollpane.setVisible(true);
            scrollPaneVisibilityHandler("menu");
        }


    }//GEN-LAST:event_menu_btnMouseClicked

    private void edit_menuBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_menuBtnMouseClicked
        // TODO add your handling code here:
        if (edit_scrollpane.isVisible()) {
            edit_scrollpane.setVisible(false);
        } else {
            edit_scrollpane.setVisible(true);
            scrollPaneVisibilityHandler("edit");
        }
    }//GEN-LAST:event_edit_menuBtnMouseClicked

    private void teams_menuBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teams_menuBtnMouseClicked
        // TODO add your handling code here:
        if (teams_scrollpane.isVisible()) {
            teams_scrollpane.setVisible(false);
        } else {
            teams_scrollpane.setVisible(true);
            scrollPaneVisibilityHandler("teams");
        }

    }//GEN-LAST:event_teams_menuBtnMouseClicked

    private void match_menuBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_match_menuBtnMouseClicked
        // TODO add your handling code here:
        if (match_scrollpane.isVisible()) {
            match_scrollpane.setVisible(false);
        } else {
            match_scrollpane.setVisible(true);
            scrollPaneVisibilityHandler("match");
        }

    }//GEN-LAST:event_match_menuBtnMouseClicked

    private void settings_menuBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settings_menuBtnMouseClicked
        // TODO add your handling code here:
        if (settings_scrollpane.isVisible()) {
            settings_scrollpane.setVisible(false);
        } else {
            settings_scrollpane.setVisible(true);
            scrollPaneVisibilityHandler("settings");
        }
    }//GEN-LAST:event_settings_menuBtnMouseClicked

    private void teams_listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_teams_listValueChanged

        // TODO add your handling code here:
        if (evt.getValueIsAdjusting()) {

            System.out.println("com.scoring.GUI.MainScoringForm.teams_listValueChanged()=================== callled");

            if (teams_list.getSelectedValue() == "Choose Teams") {

                teams_scrollpane.setVisible(false);
                TeamMatchVariables.tournamentType = teams_list.getSelectedValue();
                new TeamSelectionForm().setVisible(true);

            } else if (teams_list.getSelectedValue() == "Add Players") {

                teams_scrollpane.setVisible(false);
                TeamMatchVariables.tournamentType = teams_list.getSelectedValue();
                new PlayerSelectionForm().setVisible(true);

            } else {

                teams_scrollpane.setVisible(false);
                TeamMatchVariables.tournamentType = teams_list.getSelectedValue();
                new ChooseCaptainForm().setVisible(true);

            }

        }

    }//GEN-LAST:event_teams_listValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScoringForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScoringForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScoringForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScoringForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScoringForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> edit_list;
    private javax.swing.JMenu edit_menuBtn;
    private javax.swing.JScrollPane edit_scrollpane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JList<String> match_list;
    private javax.swing.JMenu match_menuBtn;
    private javax.swing.JScrollPane match_scrollpane;
    private javax.swing.JMenu menu_btn;
    private javax.swing.JList<String> menu_list;
    private javax.swing.JScrollPane menu_scrollpane;
    private javax.swing.JList<String> settings_list;
    private javax.swing.JMenu settings_menuBtn;
    private javax.swing.JScrollPane settings_scrollpane;
    private javax.swing.JList<String> teams_list;
    private javax.swing.JMenu teams_menuBtn;
    private javax.swing.JScrollPane teams_scrollpane;
    // End of variables declaration//GEN-END:variables
}
