/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.scoring.GUI;

import com.scoring.GUI.panels.TossConfirmPanel;
import com.scoring.globalvariables.GlobalVariables;
import com.scoring.globalvariables.TeamMatchVariables;
import com.scoring.threadOperations.BeforeMatchThreadOperatins;
import java.awt.Color;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.Map;
import java.util.Set;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author AuroLed
 */
public class MainScoringForm extends javax.swing.JFrame {

    /**
     * Creates new form MainScoringForm
     */
    private BeforeMatchThreadOperatins beforeMatchThreadOperatins;

    private String stadimName = null;
    private String stadiumCity = null;

    public MainScoringForm() {

        initComponents();
        this.getContentPane().setBackground(new Color(29, 99, 97));
        this.setBounds(0, 0, 1300, 720);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        loadOperations();
        match_confirm_panel.setBackground(new Color(66, 125, 102));
        match_confirm_panel.setBounds(50, 50, 1200, 620);
        match_confirm_panel.setVisible(false);

        beforeMatchThreadOperatins = new BeforeMatchThreadOperatins();
        beforeMatchThreadOperatins.callBeforeMatchThread();
        
        GlobalVariables.mainScoringForm = this;
    }

    private void loadOperations() {
        menu_scrollpane.setVisible(false);
        edit_scrollpane.setVisible(false);
        teams_scrollpane.setVisible(false);
        match_scrollpane.setVisible(false);
        settings_scrollpane.setVisible(false);
    }

    private void scrollPaneVisibilityHandler(String menuType) {

        System.out.println("function called called ");

        if (menuType == "menu") {

            edit_scrollpane.setVisible(false);
            teams_scrollpane.setVisible(false);
            match_scrollpane.setVisible(false);
            settings_scrollpane.setVisible(false);

        } else if (menuType == "edit") {

            menu_scrollpane.setVisible(false);
            teams_scrollpane.setVisible(false);
            match_scrollpane.setVisible(false);
            settings_scrollpane.setVisible(false);

        } else if (menuType == "teams") {

            menu_scrollpane.setVisible(false);
            edit_scrollpane.setVisible(false);
            match_scrollpane.setVisible(false);
            settings_scrollpane.setVisible(false);

        } else if (menuType == "match") {

            menu_scrollpane.setVisible(false);
            edit_scrollpane.setVisible(false);
            teams_scrollpane.setVisible(false);
            settings_scrollpane.setVisible(false);

        } else if (menuType == "settings") {

            menu_scrollpane.setVisible(false);
            edit_scrollpane.setVisible(false);
            teams_scrollpane.setVisible(false);
            match_scrollpane.setVisible(false);
//            settings_scrollpane.setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_scrollpane = new javax.swing.JScrollPane();
        menu_list = new javax.swing.JList<>();
        edit_scrollpane = new javax.swing.JScrollPane();
        edit_list = new javax.swing.JList<>();
        teams_scrollpane = new javax.swing.JScrollPane();
        teams_list = new javax.swing.JList<>();
        match_scrollpane = new javax.swing.JScrollPane();
        match_list = new javax.swing.JList<>();
        settings_scrollpane = new javax.swing.JScrollPane();
        settings_list = new javax.swing.JList<>();
        match_confirm_panel = new javax.swing.JPanel();
        month = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        home_team_field = new javax.swing.JTextField();
        away_team_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        total_innings_over = new javax.swing.JTextField();
        stadium_combo_list = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        stadium_city = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tv_umpire = new javax.swing.JTextField();
        on_field_ump1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        onfield_ump2 = new javax.swing.JTextField();
        confirm_match_btn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        match_no = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_btn = new javax.swing.JMenu();
        edit_menuBtn = new javax.swing.JMenu();
        teams_menuBtn = new javax.swing.JMenu();
        match_menuBtn = new javax.swing.JMenu();
        settings_menuBtn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu_list.setBackground(new java.awt.Color(76, 133, 131));
        menu_list.setForeground(new java.awt.Color(255, 255, 255));
        menu_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        menu_list.setName(""); // NOI18N
        menu_scrollpane.setViewportView(menu_list);

        getContentPane().add(menu_scrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 104, -1));

        edit_list.setBackground(new java.awt.Color(76, 133, 131));
        edit_list.setForeground(new java.awt.Color(255, 255, 255));
        edit_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        edit_scrollpane.setViewportView(edit_list);

        getContentPane().add(edit_scrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 100, -1));

        teams_list.setBackground(new java.awt.Color(76, 133, 131));
        teams_list.setForeground(new java.awt.Color(255, 255, 255));
        teams_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Choose Teams", "Add Players", "Select Captain" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        teams_list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                teams_listValueChanged(evt);
            }
        });
        teams_scrollpane.setViewportView(teams_list);

        getContentPane().add(teams_scrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 0, 107, -1));

        match_list.setBackground(new java.awt.Color(76, 133, 131));
        match_list.setForeground(new java.awt.Color(255, 255, 255));
        match_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Start Match", "Load Previus Match" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        match_list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                match_listValueChanged(evt);
            }
        });
        match_scrollpane.setViewportView(match_list);

        getContentPane().add(match_scrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 0, -1, -1));

        settings_list.setBackground(new java.awt.Color(76, 133, 131));
        settings_list.setForeground(new java.awt.Color(255, 255, 255));
        settings_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        settings_scrollpane.setViewportView(settings_list);

        getContentPane().add(settings_scrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 0, 100, -1));

        match_confirm_panel.setBackground(new java.awt.Color(204, 204, 255));
        match_confirm_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        month.setToolTipText("Month");
        match_confirm_panel.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 30, 30));

        date.setToolTipText("Date");
        match_confirm_panel.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 30, 30));

        year.setToolTipText("Year");
        match_confirm_panel.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 70, 30));

        jLabel1.setText("Date :");
        match_confirm_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));
        match_confirm_panel.add(home_team_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 200, 30));
        match_confirm_panel.add(away_team_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 200, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Match Between");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        match_confirm_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 190, 20));

        jLabel3.setText("VS");
        match_confirm_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, 20));

        jLabel4.setText("Total Overs :");
        match_confirm_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 70, 30));
        match_confirm_panel.add(total_innings_over, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 50, 30));

        stadium_combo_list.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                stadium_combo_listItemStateChanged(evt);
            }
        });
        stadium_combo_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stadium_combo_listActionPerformed(evt);
            }
        });
        match_confirm_panel.add(stadium_combo_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 220, 30));

        jLabel5.setText("Stadium");
        match_confirm_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 110, -1));
        match_confirm_panel.add(stadium_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 150, 30));

        jLabel6.setText("On Field Umpires");
        match_confirm_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 120, 20));
        match_confirm_panel.add(tv_umpire, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 150, 30));
        match_confirm_panel.add(on_field_ump1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 150, 30));

        jLabel7.setText("1");
        match_confirm_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 20, 20));

        jLabel8.setText("2");
        match_confirm_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 20, 20));

        jLabel9.setText("TV Umpires");
        match_confirm_panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 110, 20));
        match_confirm_panel.add(onfield_ump2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 150, 30));

        confirm_match_btn.setText("CONFIRM");
        confirm_match_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_match_btnActionPerformed(evt);
            }
        });
        match_confirm_panel.add(confirm_match_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 403, 160, 30));

        jLabel10.setText("city");
        match_confirm_panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        jLabel11.setText("Match No :");
        match_confirm_panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, 30));
        match_confirm_panel.add(match_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 50, 30));

        getContentPane().add(match_confirm_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1300, 600));

        jMenuBar1.setBackground(new java.awt.Color(106, 130, 138));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setAlignmentX(1.0F);
        jMenuBar1.setAlignmentY(1.0F);
        jMenuBar1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(1, 2, 2, 2));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(120, 25));

        menu_btn.setText("Menu           ");
        menu_btn.setMaximumSize(new java.awt.Dimension(110, 32767));
        menu_btn.setPreferredSize(new java.awt.Dimension(100, 19));
        menu_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_btnMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_btn);

        edit_menuBtn.setText("Edit            ");
        edit_menuBtn.setMaximumSize(new java.awt.Dimension(110, 32767));
        edit_menuBtn.setPreferredSize(new java.awt.Dimension(100, 19));
        edit_menuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_menuBtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(edit_menuBtn);

        teams_menuBtn.setText("Teams");
        teams_menuBtn.setMaximumSize(new java.awt.Dimension(110, 32767));
        teams_menuBtn.setPreferredSize(new java.awt.Dimension(100, 19));
        teams_menuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teams_menuBtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(teams_menuBtn);

        match_menuBtn.setText("Match");
        match_menuBtn.setMaximumSize(new java.awt.Dimension(120, 32767));
        match_menuBtn.setPreferredSize(new java.awt.Dimension(110, 19));
        match_menuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                match_menuBtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(match_menuBtn);

        settings_menuBtn.setText("Settings                   ");
        settings_menuBtn.setMaximumSize(new java.awt.Dimension(120, 32767));
        settings_menuBtn.setPreferredSize(new java.awt.Dimension(110, 19));
        settings_menuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settings_menuBtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(settings_menuBtn);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_btnMouseClicked
        // TODO add your handling code here:

        if (menu_scrollpane.isVisible()) {
            menu_scrollpane.setVisible(false);
        } else {
            menu_scrollpane.setVisible(true);
            scrollPaneVisibilityHandler("menu");
        }


    }//GEN-LAST:event_menu_btnMouseClicked

    private void edit_menuBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_menuBtnMouseClicked
        // TODO add your handling code here:
        if (edit_scrollpane.isVisible()) {
            edit_scrollpane.setVisible(false);
        } else {
            edit_scrollpane.setVisible(true);
            scrollPaneVisibilityHandler("edit");
        }
    }//GEN-LAST:event_edit_menuBtnMouseClicked

    private void teams_menuBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teams_menuBtnMouseClicked
        // TODO add your handling code here:
        if (teams_scrollpane.isVisible()) {
            teams_scrollpane.setVisible(false);
        } else {
            teams_scrollpane.setVisible(true);
            scrollPaneVisibilityHandler("teams");
        }

    }//GEN-LAST:event_teams_menuBtnMouseClicked

    private void match_menuBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_match_menuBtnMouseClicked
        // TODO add your handling code here:
        if (match_scrollpane.isVisible()) {
            match_scrollpane.setVisible(false);
        } else {
            match_scrollpane.setVisible(true);
            scrollPaneVisibilityHandler("match");
        }

    }//GEN-LAST:event_match_menuBtnMouseClicked

    private void settings_menuBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settings_menuBtnMouseClicked
        // TODO add your handling code here:
        if (settings_scrollpane.isVisible()) {
            settings_scrollpane.setVisible(false);
        } else {
            settings_scrollpane.setVisible(true);
            scrollPaneVisibilityHandler("settings");
        }
    }//GEN-LAST:event_settings_menuBtnMouseClicked

    private void teams_listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_teams_listValueChanged

        // TODO add your handling code here:
        if (evt.getValueIsAdjusting()) {

            System.out.println("com.scoring.GUI.MainScoringForm.teams_listValueChanged()=================== callled");

            if (teams_list.getSelectedValue() == "Choose Teams") {

                teams_scrollpane.setVisible(false);
                TeamMatchVariables.tournamentType = teams_list.getSelectedValue();
                new TeamSelectionForm().setVisible(true);

            } else if (teams_list.getSelectedValue() == "Add Players") {

                teams_scrollpane.setVisible(false);
                TeamMatchVariables.tournamentType = teams_list.getSelectedValue();
                new PlayerSelectionForm().setVisible(true);

            } else {

                teams_scrollpane.setVisible(false);
                TeamMatchVariables.tournamentType = teams_list.getSelectedValue();
                new ChooseCaptainForm().setVisible(true);

            }

        }

    }//GEN-LAST:event_teams_listValueChanged

    private void match_listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_match_listValueChanged
        // TODO add your handling code here:

        if (evt.getValueIsAdjusting()) {

            if (match_list.getSelectedValue().equals("Start Match")) {
                match_confirm_panel.setVisible(true);
                match_scrollpane.setVisible(false);

                loadStadiumsToComboList();

            }
        }

    }//GEN-LAST:event_match_listValueChanged

    private void confirm_match_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_match_btnActionPerformed
        // TODO add your handling code here:

        if (match_no.getText() != null && date.getText() != null && month.getText() != null && year.getText() != null
                && stadium_combo_list.getSelectedItem() != null) {

            TeamMatchVariables.currentMatchDetails.setMatch_no(Short.valueOf(match_no.getText()));

            Date matchDate = getSqlDate(date.getText() + "-" + month.getText() + "-" + year.getText());

            TeamMatchVariables.currentMatchDetails.setMatchDate(matchDate);

            TeamMatchVariables.currentMatchDetails.setStadium(stadium_combo_list.getSelectedItem().toString());
            TeamMatchVariables.currentMatchDetails.setCity(stadium_city.getText());
            TeamMatchVariables.currentMatchDetails.setTv_umpires(tv_umpire.getText());
            TeamMatchVariables.currentMatchDetails.setUmpires(on_field_ump1.getText() + " " + onfield_ump2.getText());
            match_confirm_panel.setVisible(false);
          

            try {
                this.add(new TossConfirmPanel());
            } catch (Exception e) {
                e.printStackTrace();
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Please Enter Th Required Fields To Continue", "Some Fields Are Emtpty", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_confirm_match_btnActionPerformed

    private void stadium_combo_listItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_stadium_combo_listItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_stadium_combo_listItemStateChanged

    private void stadium_combo_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stadium_combo_listActionPerformed
        // TODO add your handling code here:
        stadimName = stadium_combo_list.getSelectedItem().toString();
        stadiumCity = TeamMatchVariables.stadiumsMap.get(stadimName);

        stadium_city.setText(stadiumCity);
    }//GEN-LAST:event_stadium_combo_listActionPerformed

    public static Date getSqlDate(String stringDate) {
        
        System.out.println(" = - = - = - = - = - = - = - = - = - = - = - = - =" +stringDate);

        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        Date sqlDate = null;
        try {
            java.util.Date utlDate = sdf.parse(stringDate);
            sqlDate = new Date(utlDate.getTime());

        } catch (Exception e) {
            System.out.println("date format error");
            e.printStackTrace();
        }

        return sqlDate;

    }

    private void loadStadiumsToComboList() {
        
        home_team_field.setText(TeamMatchVariables.homeTeam);
        away_team_field.setText(TeamMatchVariables.awayTeam);

//        DefaultComboBoxModel<String> defaultComboBoxModel = new DefaultComboBoxModel<>();
        for (String stadium : TeamMatchVariables.stadiumsMap.keySet()) {
//            defaultComboBoxModel.addElement(stadium);
            stadium_combo_list.addItem(stadium);
        }

    }

    /**
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScoringForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScoringForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScoringForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScoringForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScoringForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField away_team_field;
    private javax.swing.JButton confirm_match_btn;
    private javax.swing.JTextField date;
    private javax.swing.JList<String> edit_list;
    private javax.swing.JMenu edit_menuBtn;
    private javax.swing.JScrollPane edit_scrollpane;
    private javax.swing.JTextField home_team_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel match_confirm_panel;
    private javax.swing.JList<String> match_list;
    private javax.swing.JMenu match_menuBtn;
    private javax.swing.JTextField match_no;
    private javax.swing.JScrollPane match_scrollpane;
    private javax.swing.JMenu menu_btn;
    private javax.swing.JList<String> menu_list;
    private javax.swing.JScrollPane menu_scrollpane;
    private javax.swing.JTextField month;
    private javax.swing.JTextField on_field_ump1;
    private javax.swing.JTextField onfield_ump2;
    private javax.swing.JList<String> settings_list;
    private javax.swing.JMenu settings_menuBtn;
    private javax.swing.JScrollPane settings_scrollpane;
    private javax.swing.JTextField stadium_city;
    private javax.swing.JComboBox<String> stadium_combo_list;
    private javax.swing.JList<String> teams_list;
    private javax.swing.JMenu teams_menuBtn;
    private javax.swing.JScrollPane teams_scrollpane;
    private javax.swing.JTextField total_innings_over;
    private javax.swing.JTextField tv_umpire;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
