/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.scoring.GUI;

import com.scoring.globalvariables.TeamMatchVariables;
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author AuroLed
 */
public class PlayerSelectionForm extends javax.swing.JFrame {

    /**
     * Creates new form PlayerSelectionForm
     */
    
    private String selectedTeamToAddPlayers = null;
    public PlayerSelectionForm() {
        initComponents();
        
        this.setSize(700, 500);
        this.getContentPane().setBackground(new Color(63, 115, 113));
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        getPlayersOfBothTeam();
        
        addTeamsToSelectionList();
    }
    
    private void getPlayersOfBothTeam() {
        
    }
    
    private void addTeamsToSelectionList() {
        
        DefaultListModel<String> defaultListModel = new DefaultListModel<>();
        
        
        
        defaultListModel.addElement(TeamMatchVariables.homeTeam);
        defaultListModel.addElement(TeamMatchVariables.awayTeam);
        
        selectedTeamToAddPlayers = TeamMatchVariables.homeTeam;
        
        if (selectedTeamToAddPlayers != null) {
            addPlayersToList();
        }
        
        team_selection_list.setModel(defaultListModel);
    }

    private void addPlayersToList() {
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player_selection_panel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        team_selection_list = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        player_selection_panel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        player_selection_panel.setForeground(new java.awt.Color(135, 30, 1));
        player_selection_panel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player_selection_panel.setText("Choose Players Here");
        getContentPane().add(player_selection_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 230, 32));

        team_selection_list.setBackground(new java.awt.Color(116, 153, 152));
        team_selection_list.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jScrollPane1.setViewportView(team_selection_list);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 250, 60));

        jList1.setBackground(new java.awt.Color(116, 153, 152));
        jList1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 250, 230));

        jLabel1.setText("Select Team");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 20));

        jLabel2.setText("Players");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerSelectionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerSelectionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerSelectionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerSelectionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerSelectionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel player_selection_panel;
    private javax.swing.JList<String> team_selection_list;
    // End of variables declaration//GEN-END:variables
}
